## Notwendige Importe

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Daten laden und vorbereiten

In [2]:
data_path = 'Bewässerungszeiten-Datensatz/Bewässerungszeiten-Datensatz_small_31722.csv'
rides = pd.read_csv(data_path)

In [3]:
rides.head()

,instant,season,yr,mnth,hr,b12h_weathersit,b9h_weathersit,b6h_weathersit,b3h_weathersit,crnt_weathersit,...,a6h_weathersit,a9h_weathersit,a12h_weathersit,temp,atemp,hum,soil_hum,windspeed,CNN_decision,conclusion
0,1.0,1,0,1,0,1,1,1,1,1,...,1,1,1,0.24,0.2879,0.81,0.81,0.0,1,1
1,2.0,1,0,1,1,1,1,1,1,1,...,1,1,2,0.22,0.2727,0.80,0.80,0.0,1,1
2,3.0,1,0,1,2,1,1,1,1,1,...,1,1,2,0.22,0.2727,0.80,0.80,0.0,1,1
3,4.0,1,0,1,3,1,1,1,1,1,...,1,1,2,0.24,0.2879,0.75,0.75,0.0,1,1
4,5.0,1,0,1,4,1,1,1,1,1,...,1,2,2,0.24,0.2879,0.75,0.75,0.0,1,1

In [4]:
dummy_fields = ['season', 'b12h_weathersit', 'b9h_weathersit', 'b6h_weathersit', 'b3h_weathersit', 
                'crnt_weathersit', 'a3h_weathersit', 'a6h_weathersit', 'a9h_weathersit', 'a12h_weathersit', 
                'mnth', 'hr']


for each in dummy_fields:
    dummies = pd.get_dummies(rides[each], prefix=each, drop_first=False)
    rides = pd.concat([rides, dummies], axis=1)

fields_to_drop = ['instant',  'season', 'b12h_weathersit', 'b9h_weathersit', 'b6h_weathersit', 'b3h_weathersit', 
                'crnt_weathersit', 'a3h_weathersit', 'a6h_weathersit', 'a9h_weathersit', 'a12h_weathersit', 
                'mnth', 'hr']

data = rides.drop(fields_to_drop, axis=1)
data.head()

,yr,temp,atemp,hum,soil_hum,windspeed,CNN_decision,conclusion,season_1,season_2,...,hr_14,hr_15,hr_16,hr_17,hr_18,hr_19,hr_20,hr_21,hr_22,hr_23
0,0,0.24,0.2879,0.81,0.81,0.0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0.22,0.2727,0.80,0.80,0.0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0.22,0.2727,0.80,0.80,0.0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0.24,0.2879,0.75,0.75,0.0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0.24,0.2879,0.75,0.75,0.0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# shuffle the DataFrame rows
data = data.sample(frac = 1)
data.head()

,yr,temp,atemp,hum,soil_hum,windspeed,CNN_decision,conclusion,season_1,season_2,...,hr_14,hr_15,hr_16,hr_17,hr_18,hr_19,hr_20,hr_21,hr_22,hr_23
5651,1,0.56,0.5303,0.60,0.60,0.1642,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6114,1,0.62,0.5909,0.78,0.78,0.1940,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3101,0,0.56,0.5303,0.88,0.88,0.0000,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1879,0,0.50,0.4848,0.88,0.88,0.1642,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
650,0,0.18,0.2424,0.80,0.80,0.0000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

## Skalierung ein kontinuierliches Merkmal
Abgebrochen, weil es die Leistung des Modells nicht verbessert

quant_features = ['temp', 'atemp', 'hum', 'soil_hum', 'windspeed', ]
# Store scalings in a dictionary so we can convert back later
scaled_features = {}
for each in quant_features:
    mean, std = data[each].mean(), data[each].std()
    scaled_features[each] = [mean, std]
    data.loc[:, each] = (data[each] - mean)/std

## Daten in Trainings-, Validierungs- und Testsätze aufteilen

In [6]:
# Save data for approximately the last 21 days 
test_data = data[-21*24:]

# Now remove the test data from the data set 
data = data[:-21*24]

# Separate the data into features and targets
target_fields = ['conclusion']
features, targets = data.drop(target_fields, axis=1), data[target_fields]
test_features, test_targets = test_data.drop(target_fields, axis=1), test_data[target_fields]

In [7]:
features.head()

,yr,temp,atemp,hum,soil_hum,windspeed,CNN_decision,season_1,season_2,season_3,...,hr_14,hr_15,hr_16,hr_17,hr_18,hr_19,hr_20,hr_21,hr_22,hr_23
5651,1,0.56,0.5303,0.60,0.60,0.1642,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6114,1,0.62,0.5909,0.78,0.78,0.1940,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3101,0,0.56,0.5303,0.88,0.88,0.0000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1879,0,0.50,0.4848,0.88,0.88,0.1642,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
650,0,0.18,0.2424,0.80,0.80,0.0000,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
# Hold out the last 60 days data or so of the remaining data as a validation set
train_features, train_targets = features[:-60*24], targets[:-60*24]
val_features, val_targets = features[-60*24:], targets[-60*24:]

In [9]:
# Activation (sigmoid) function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_prime(x):
    return sigmoid(x) * (1-sigmoid(x))
def error_formula(y, output):
    return - (y*np.log(output) + (1 - y) * np.log(1-output))
def error_term_formula(x, y, output):
    return (y - output)*sigmoid_prime(x)

## Netzwerk-Trainer-Funktion

In [10]:
# Training function
def train_nn(features, targets, learnrate, weights):

    n_records, n_features = features.shape
    last_loss = None

#     # Initialize weights
#     np.random.seed(42)
#     weights = np.random.normal( scale = 1 / n_features**.5, size=n_features )
    
    del_w = np.zeros(weights.shape)
    for x, y in zip(features, targets):
        
        output = sigmoid(np.dot(x, weights))
            
        # The error, the target minus the network output
        error = error_formula(y, output)

        # The error term
        error_term = error_term_formula(x, y, output)

        # The gradient descent step, the error times the gradient times the inputs
        del_w += error_term * x

    # Update the weights 
    weights += learnrate * del_w / n_records
        
    return weights

## Network Runner

In [11]:
def run_nn(x, weights):
    output = sigmoid(np.dot(x, weights))
    return np.rint(output) # round to the nearest integer

## Trainiere das Netzwerk

In [12]:
import sys
# Neural Network hyperparameters
epochs = 300
learnrate = 0.5

n_records, n_features = train_features.shape
# Use to same seed to make debugging easier
np.random.seed(42)
# Initialize weights
weights = np.random.normal( scale = 1 / n_features**.5, size=n_features )

for e in range(epochs):
    # train network and get new weights
    weights = train_nn(train_features.to_numpy(), train_targets.loc[:]['conclusion'].to_numpy(), learnrate, weights)
    # validate the network 
    output = run_nn(val_features.to_numpy(), weights)
    evaluation = output==val_targets.loc[:]['conclusion'].to_numpy()
    if e % 10 == 0:
        # mean square error on the training set    
        out = sigmoid(np.dot(train_features.to_numpy(), weights))
        train_loss = np.mean((out - train_targets.loc[:]['conclusion'].to_numpy()) ** 2)
        # mean square error on the validation set
        out = sigmoid(np.dot(val_features.to_numpy(), weights))
        val_loss = np.mean((out - val_targets.loc[:]['conclusion'].to_numpy()) ** 2)
        sys.stdout.write("\rEpoch: {:2d}".format(e) \
                     + " ... Training loss: " + str(train_loss)[:6] \
                     + " ... Validation loss: " + str(val_loss)[:6])
        sys.stdout.flush()

Epoch: 290 ... Training loss: 0.0294 ... Validation loss: 0.0253

## Netzwerk testen

In [13]:
evaluation = []
for x, y in zip(test_features.to_numpy(), test_targets.loc[:]['conclusion'].to_numpy()):
    output = run_nn(x, weights)
    evaluation.append(output==y)
acc = np.sum(evaluation)/len(evaluation)
print("Test accuracy :", acc)

Test accuracy : 0.9841269841269841

## Gewichte speichern und laden

In [14]:
# save to csv file
np.savetxt('nn_weights.csv', weights, delimiter=',')

In [15]:
# load from csv file
weights = np.loadtxt('nn_weights.csv', delimiter=',')

In [16]:
evaluation = []
for x, y in zip(test_features.to_numpy(), test_targets.loc[:]['conclusion'].to_numpy()):
    output = run_nn(x, weights)
#     print(output)
    evaluation.append(output==y)
np.sum(evaluation)/len(evaluation)

0.9841269841269841

## Testmodell mit handgemachten Daten

In [17]:
def decider(weights, CNN_decision, s_humidity, csv_path = 'temporary_data_.csv'):
    example = {
           'season': [2],
           'yr': [0], 
           'mnth': [7],
           'hr': [18], 
           'b12h_weathersit': [2],
           'b9h_weathersit': [2], 
           'b6h_weathersit': [2],
           'b3h_weathersit': [2], 
           'crnt_weathersit': [2],
           'a3h_weathersit': [2], 
           'a6h_weathersit': [2],
           'a9h_weathersit': [2], 
           'a12h_weathersit': [2],
           'temp': [0.5], 
           'atemp': [0.5],
           'hum': [s_humidity], 
           'soil_hum': [s_humidity],
           'windspeed': [0.2], 
           'CNN_decision': [CNN_decision]
          }
    # convert dictionary to pandas dataframe
    example = pd.DataFrame.from_dict(example)
    # add example to csv file
    example.to_csv(csv_path, mode='a', header=False)
    # read csv file
    rides = pd.read_csv(csv_path)
    # normalize data
    dummy_fields = ['season', 'b12h_weathersit', 'b9h_weathersit', 'b6h_weathersit', 'b3h_weathersit', 
                'crnt_weathersit', 'a3h_weathersit', 'a6h_weathersit', 'a9h_weathersit', 'a12h_weathersit', 
                'mnth', 'hr']
    for each in dummy_fields:
        dummies = pd.get_dummies(rides[each], prefix=each, drop_first=False)
        rides = pd.concat([rides, dummies], axis=1)
    fields_to_drop = ['instant',  'season', 'b12h_weathersit', 'b9h_weathersit', 'b6h_weathersit', 'b3h_weathersit', 
                    'crnt_weathersit', 'a3h_weathersit', 'a6h_weathersit', 'a9h_weathersit', 'a12h_weathersit', 
                    'mnth', 'hr', 'conclusion']
    data = rides.drop(fields_to_drop, axis=1)
#     print(data)
    # Convert dataframe to numpy and get last data from list
    data = data.to_numpy()[-1]    
    # run second model to decition
    decition = run_nn(data, weights)
    
    return decition

In [18]:
decider(weights, 
        CNN_decision = 0,        
        s_humidity = 0.5,
        csv_path = 'temporary_data_.csv')

0.0